# Generated by Django 5.0.1 on 2024-01-24 10:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50, verbose_name='Customer Name')),
                ('date', models.DateField(default=datetime.date(2024, 1, 24), verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Invoice Description')),
                ('quantity', models.IntegerField(verbose_name='Qunatity(No of Units)')),
                ('unit_price', models.IntegerField(verbose_name='Unit Price')),
                ('price', models.BigIntegerField(verbose_name='Total Price')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_apis.invoice')),
            ],
        ),
    ]
